# Generated by Django 5.2 on 2025-04-22 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options_rename_author_book_authors_and_more'),
        ('bookmark', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='book',
            new_name='books',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'books')},
        ),
    ]
