# Generated by Django 5.2 on 2025-04-24 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options_rename_author_book_authors_and_more'),
        ('bookmark', '0002_rename_book_bookmark_books_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='books',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'book')},
        ),
    ]
