# Generated by Django 5.2 on 2025-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.ManyToManyField(related_name='books', to='author.author')),
                ('genres', models.ManyToManyField(related_name='books', to='genres.genre')),
            ],
        ),
    ]
