# Generated by Django 5.2 on 2025-04-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
    ]
