# Generated by Django 5.2 on 2025-04-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_genres'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='genres.genre'),
        ),
    ]
